# basic config

base_url: 'https://berlin.github.io' # the base hostname & protocol for your site, e.g. http://example.com
base_path: '/lod-budget' # the subpath of your site, e.g. /blog
dataset_path: 'data/temp/all.nt'
template_path: 'templates'
output_path: '_site/'
prefixes:
  berorgs: https://berlin.github.io/lod-vocabulary/berorgs/
  cube: https://cube.link/
  dct: http://purl.org/dc/terms/
  foaf: http://xmlns.com/foaf/0.1/
  hh: https://ld.example.com/bund/finanz/haushalt/
  hhbe: https://berlin.github.io/lod-budget/
  lodsg: https://berlinonline.github.io/lod-sg/
  lor: https://berlinonline.github.io/lod-berlin-lor/
  meta: https://cube.link/meta/
  org: http://www.w3.org/ns/org#
  qudt: http://qudt.org/schema/qudt/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  schema: https://schema.org/
  sdmxdim: http://purl.org/linked-data/sdmx/2009/dimension#
  skos: http://www.w3.org/2004/02/skos/core#
  vcard: http://www.w3.org/2006/vcard/ns#
  void: http://rdfs.org/ns/void#
  xsd: http://www.w3.org/2001/XMLSchema#
include:
  - assets/
class_template_mappings:
  "void:Dataset": "dataset.html.jinja"
