PREFIX sdmxdim: <http://purl.org/linked-data/sdmx/2009/dimension#>
PREFIX cube: <https://cube.link/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# which years are referenced in the data?

SELECT DISTINCT ?year ?type (COUNT(?s) AS ?amount)
WHERE {
    ?s
        sdmxdim:refPeriod ?year ;
        a ?type

}
GROUP BY ?type ?year
ORDER BY ?year ?type